export const colors = {
  purple:        '#7F77DD',
  purpleLight:   '#EEEDFE',
  purpleDark:    '#534AB7',
  teal:          '#1D9E75',
  tealLight:     '#E1F5EE',
  tealDark:      '#0F6E56',
  amber:         '#EF9F27',
  amberLight:    '#FAEEDA',
  amberDark:     '#854F0B',
  green:         '#C0DD97',
  gray:          '#D3D1C7',
  border:        'rgba(0,0,0,0.08)',
  bg:            '#F5F5F2',
  bgCard:        '#FFFFFF',
  bgSecondary:   '#F0EEE8',
  textPrimary:   '#1A1A18',
  textSecondary: '#6B6A64',
  textTertiary:  '#9E9D97',
} as const;
